name    'saz-thin'
version '1.0.0'
source 'git://github.com/saz/puppet-thin.git'
author 'saz'
license 'Apache License, Version 2.0'
summary 'Manage thin (http://code.macournoyer.com/thin/) via puppet'
description 'Manage thin (http://code.macournoyer.com/thin/) via puppet'
project_page 'https://github.com/saz/puppet-thin'
